# Your Personal Information
first_name: Lorem
last_name: Jain
full_name: Lorem Jain
job_title: Software Engineer
technology: Salesforce
location: India
image: "https://via.placeholder.com/150"
city: Bangalore
country: Indonesia
contact_no: "(+62) 812-345-678-90"
email: your-email@domain.com
website: https://example.com
social_media:
  - name: Facebook
    icon: fab fa-facebook
    handle: loremjain
    url: https://web.facebook.com/loremjain
  - name: Twitter
    icon: fab fa-twitter
    handle: lorem_jain
    url: https://twitter.com/lorem_jain
  - name: LinkedIn
    icon: fab fa-linkedin
    handle: lorem-jain
    url: https://www.linkedin.com/in/lorem-jain
  - name: GitHub
    icon: fab fa-github
    handle: loremjain
    url: https://github.com/loremjain

# Summary Section
summary:
  icon: 'fas fa-home'  # Font Awesome icon for summary section
  content: >
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin feugiat risus sit amet enim consectetur, a condimentum lectus convallis. Nam id aliquam sapien. Nulla facilisi. Sed imperdiet dolor nec mauris luctus, vel maximus risus eleifend. Donec eget lacus sed orci convallis maximus. Nam nec orci arcu. Duis vitae quam vitae orci condimentum accumsan. In hac habitasse platea dictumst.

# Experience Section
experience:
  icon: 'fas fa-briefcase'  # Font Awesome icon for experience section
  items:
    - company: Example Company
      logo: https://via.placeholder.com/150
      location: Jakarta, Indonesia
      position: Software Engineer
      duration: January 2020 - Present
      details:
        - Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        - Mauris et velit ac ligula efficitur rutrum.
        - Suspendisse cursus mauris id justo convallis, vitae posuere arcu ultrices.
        - Vestibulum quis lectus sit amet est tincidunt tempus.

# Education Section
education:
  icon: 'fas fa-user-graduate'  # Font Awesome icon for education section
  items:
    - institution: Lorem Ipsum University
      image: https://via.placeholder.com/150
      location: Ipsum City, Ipsum
      degree: Bachelor of Technology
      duration: 2014 - 2018
      details: Computer Science Engineering
      cgpa: 8.5

# Achievements Section
achievements:
  items:
    - title: Outstanding Performance Award
      subtitle: Project Management
      icon: https://via.placeholder.com/150
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - title: Innovation Excellence Award
      subtitle: Cloud Infrastructure
      icon: https://via.placeholder.com/150
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.

# Projects Section
projects:
  icon: 'fas fa-project-diagram'  # Font Awesome icon for projects section
  items:
    - name: Project A
      duration: January 2019 - December 2019
      type: Full-time
      logo: https://via.placeholder.com/150
      summary: >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin feugiat risus sit amet enim consectetur, a condimentum lectus convallis.
    - name: Project B
      duration: January 2018 - December 2018
      type: Full-time
      logo: https://via.placeholder.com/150
      summary: >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin feugiat risus sit amet enim consectetur, a condimentum lectus convallis.

# Skills Section
skills:
  icon: fas fa-graduation-cap  # Font Awesome icon for skills section
  items:
    - name: HTML
      icon: fab fa-html5
      proficiency: true
      proficiency_percent: 80
    - name: CSS
      icon: fab fa-css3
      proficiency: true
      proficiency_percent: 75
    - name: JavaScript
      icon: fab fa-js
      proficiency: true
      proficiency_percent: 85
    - name: Front-end Development
      icon: fas fa-laptop-code
      proficiency: false
    - name: React
      icon: fab fa-react
      proficiency: true
      proficiency_percent: 70
    - name: Vue.js
      icon: fab fa-vuejs
      proficiency: true
      proficiency_percent: 65

# Tools & Technologies Section
tools:
  icon: fas fa-tools  # Font Awesome icon for tools section
  items:
    - name: Adobe Photoshop
      icon: fab fa-creative-commons-sampling-plus
    - name: Figma
      icon: fas fa-paint-brush
    - name: Sketch
      icon: fas fa-palette
    - name: Adobe Illustrator
      icon: fab fa-creative-commons-by
    - name: InVision
      icon: fas fa-eye
    - name: Zeplin
      icon: fas fa-vector-square
    - name: Axure RP
      icon: fas fa-project-diagram

# Languages Section
languages:
  items:
    - name: English
      speak: true
      write: true
      read: true
    - name: French
      speak: true
      write: false
      read: true
    - name: Spanish
      speak: true
      write: true
      read: true

# Site Settings
lang: en
title: Im-Resume
title_1: Im
title_2: Resume
tagline: Open Source Resume Builder Using Bulma
logo_url: /assets/logo/im-resume.png
email: your-email@domain.com
description: >
  Open source project for creating and customizing resumes using the Bulma CSS framework.
baseurl: ""
url: "https://im-resume.example.com"
permalink: pretty

# Theme Customization
primary_color: "#E53935"
custom_theme: false

# Disqus Comments
disqus:
  shortname: im-resume

# Google AdSense
adsense: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

# Exclude Files & Directories
exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Live Reload
livereload: true

# Sass Configuration
sass:
  style: compressed
  source_dir: _sass

