first_name: Prachi
last_name: Jain
full_name: Prachi Jain
job_title: ReactJs
technology: ReactJs
location: Bangalore
image: "https://via.placeholder.com/150"
city: Bangalore
country: India
contact_no: 07355146758
email: prachi@gamil.com
website: amatrika.com
social_media:
  - name: Linkedin
    icon: fab fa-linkedin
    handle: Prachi
    url: Test
summary:
  icon: fas fa-home
  content: Test Summary
experience:
  icon: fas fa-briefcase
  items:
    - company: Test Company
      logo: "https://via.placeholder.com/150"
      location: Abad
      position: Popdu
      duration: 2018
      details:
        - Haha
education:
  icon: fas fa-user-graduate
  items:
    - institution: Popdu
      image: "https://via.placeholder.com/150"
      location: Pua
      degree: Test
      duration: ttaugjas
      details: jhagjsg
      cgpa: 78
achievements:
  items:
    - title: asgjhgas
      subtitle: ahsjhas
      icon: "https://via.placeholder.com/150"
      description: ahshashhas
projects:
  icon: fas fa-project-diagram
  items:
    - name: uyakksas
      duration: hjashjas
      type: hjadsg
      logo: "https://via.placeholder.com/150"
      summary: HJhas
skills:
  icon: fas fa-graduation-cap
  items:
    - name: gasgh
      icon: fab fa-html5
      proficiency: true
      proficiency_percent: 80
tools:
  icon: fas fa-tools
  items:
    - name: 
      icon: fab fa-creative-commons-sampling-plus
languages:
  items:
    - name: 
      speak: true
      write: true
      read: true

# Site Settings
lang: en
title: Im-Resume
title_1: Im
title_2: Resume
tagline: Open Source Resume Builder Using Bulma
logo_url: /assets/logo/im-resume.png
email: your-email@domain.com
description: >
  Open source project for creating and customizing resumes using the Bulma CSS framework.
baseurl: "/Im-Resume-Theme"
url: ""
permalink: pretty

# Theme Customization
primary_color: "#E53935"
custom_theme: false

# Disqus Comments
disqus:
  shortname: im-resume

# Google AdSense
adsense: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

# Exclude Files & Directories
exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Live Reload
livereload: true

# Sass Configuration
sass:
  style: compressed
  source_dir: _sass

